import tumeryk_guardrails

def stock_collector(user_query):
    ''' Agent that collects only a list of stocks and returns them back to the user '''
    prompt = f"""Instructions: You are a stock ticker identification agent. Respond with ONLY a list of stock tickers and company names, 
    one per line, in the format TICKER - Company Name. Return exactly 5 tickers. No analysis, no disclaimers, no markdown formatting, no explanations, no links. 
    Use your training knowledge of well-known companies.

Example response:
AAPL - Apple Inc.
MSFT - Microsoft Corporation
GOOGL - Alphabet Inc.

User request: {user_query}"""

    messages = [
        {"role": "user", "content": prompt}
    ]

    response = tumeryk_guardrails.tumeryk_completions(messages)

    tickers = response["messages"][0]["content"]
    metrics1 = response["metrics"]

    return tickers, metrics1

def research_analyst(tickers):
    ''' Agent that takes the list of stocks and provides a brief analysis on those individual stocks '''
    prompt = f"""Instructions: You are a financial research analyst. You will receive a list of stock tickers. For each ticker, provide a brief analysis covering:
1. What the company does (one sentence)
2. Recent financial performance (revenue trend, profitability)
3. Market position (leader, challenger, emerging)
4. Key risks

STRICT RULES:
- Analyze ONLY the tickers provided — do not add others
- Do NOT give buy/sell/hold recommendations — that is not your job
- Do NOT suggest websites, tools, or external resources
- Do NOT add disclaimers about consulting financial advisors
- Use your training knowledge — do not say you lack real-time data
- Keep each company's analysis to 3-4 sentences
- Separate each company with a blank line
- Do NOT use markdown formatting like bold, headers, or bullet points

Tickers to analyze:
{tickers}"""
    
    messages = [
        {"role": "user", "content": prompt}
    ]
    
    response = tumeryk_guardrails.tumeryk_completions(messages)

    analysis = response["messages"][0]["content"]
    metrics2 = response["metrics"]

    return analysis, metrics2

def decision_maker(analysis):
    prompt = f"""Instructions: You are a senior investment strategist. You will receive research analysis on several stocks. For each stock, provide a trading recommendation.

For each stock, include:
1. Position: LONG (buy and hold) or SHORT (bet against) or AVOID
2. Conviction level: HIGH, MEDIUM, or LOW
3. Entry point: suggested price range to enter the position
4. Exit point: suggested price range to take profits
5. Risk level: LOW, MEDIUM, or HIGH
6. One sentence explaining your reasoning

STRICT RULES:
- Base your recommendations ONLY on the analysis provided — do not add outside information
- You MUST include a risk warning at the very end of your response
- Do NOT suggest websites, tools, or external resources
- Do NOT use markdown formatting like bold, headers, or bullet points
- Keep each recommendation to 4-5 lines maximum
- Use your training knowledge for approximate price ranges
- Be direct and specific — avoid vague language like "it depends"

Risk warning to include at the end: "DISCLAIMER: These recommendations are generated by an AI system for educational purposes only. This is not financial advice. Always conduct your own research and consult a licensed financial advisor before making investment decisions."

Analysis to evaluate:
{analysis}"""

    messages = [
        {"role": "user", "content": prompt}
    ]
    
    response = tumeryk_guardrails.tumeryk_completions(messages)

    recommendation = response["messages"][0]["content"]
    metrics3 = response["metrics"]

    return recommendation, metrics3
